name: epimetheus
catsEffectVersion: 2.0.0-RC1
shapelessVersion: 2.3.3
baseurl: /epimetheus
description: An Afterthought of Prometheus
catsVersion: 2.0.0-RC1
highlighter: rouge
docs: true
collections:
  tut:
    output: true
epimetheusVersion: 0.3.0-RC1+9-1d8ebc32-SNAPSHOT
scalaVersion: 2.12.9
version: 0.3.0-RC1+9-1d8ebc32-SNAPSHOT
scalaVersions: 2.13/12
org: io.chrisdavenport
markdown: kramdown
