name: epimetheus
catsEffectVersion: 1.3.0
shapelessVersion: 2.3.3
baseurl: /epimetheus
description: An Afterthought of Prometheus
catsVersion: 1.6.0
highlighter: rouge
docs: true
collections:
  tut:
    output: true
epimetheusVersion: 0.2.3-SNAPSHOT
scalaVersion: 2.12.8
version: 0.2.3-SNAPSHOT
scalaVersions: 2.12/11
org: io.chrisdavenport
markdown: kramdown
