name: epimetheus
baseurl: /epimetheus
description: An Afterthought of Prometheus
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.6-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
